services:
  jekyll-site:
    image: jekyll-site
    build: .
    volumes: [ .:/usr/src/app:ro ]
    ports: [ "127.0.0.1:4000:4000" ]
    user: "${LOCAL_UID:-1000}:${LOCAL_GID:-1000}"
    environment: [ JEKYLL_ENV=docker ]
    command: bundle exec jekyll serve -H 0.0.0.0 -w --force_polling --config _config.yml,_config_docker.yml --destination /tmp/jekyll-site
